.TH lxde-logout 1 "Mar 21, 2008" "lxde-logout"

.SH NAME
lxde-logout \-program for...

.SH SYNOPSIS
.B lxde-logout
.br

.SH DESCRIPTION
This manual page explains the
.B lxde-logout
program. This program is part of LXDE.
.PP
\fBlxde-logout\fP, as its name implies, is for logging out LXDE.
Running this program will show the logout dialog on the screen.

.SH SEE ALSO
startlxde

.SH AUTHOR
Hong Jen Yee <pcman.tw@gmail.com>