.TH startlxde 1 "Mar 21, 2008" "startlxde"

.SH NAME
startlxde \-program for...

.SH SYNOPSIS
.B startlxde
.RI [ options ]
.br

.SH DESCRIPTION
This manual page explains the
.B startlxde
program. This program...
.PP
\fBstartlxde\fP is used to start the desktop session of LXDE.
By default it loads openbox, lxpanel, pcmanfm, smproxy, and lxsession.

.SH AUTHOR
Hong Jen Yee <pcman.tw@gmail.com>
