.TH startlxde 1 "Mar 21, 2008" "startlxde"

.SH NAME
startlxde \- X session script to prepare environment and run lxsession.

.SH SYNOPSIS
.B startlxde
.br

.SH DESCRIPTION
.PP
\fBstartlxde\fP is used to start the desktop session of LXDE.
By default it loads openbox, lxpanel, pcmanfm, dbus-launch, and lxsession.

.SH AUTHOR
Hong Jen Yee <pcman.tw@gmail.com>
