#!/bin/sh -e

if [ "$1" = configure ]; then
  update-alternatives --install /usr/bin/x-session-manager \
    x-session-manager /usr/bin/startlxde 50 \
    --slave /usr/share/man/man1/x-session-manager.1.gz \
    x-session-manager.1.gz /usr/share/man/man1/startlxde.1.gz 

fi

#DEBHELPER#

exit 0
